version: '3.2'
services:
  app:
    image: maxisme/notifi.it:latest
    env_file:
      - ".env"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.notifiit.rule=Host(`notifi.it`)"
        - "traefik.http.routers.notifiit.entrypoints=web-secure"
        - "traefik.http.routers.notifiit.tls.certresolver=letsencrypt"
        - "traefik.http.services.notifiit.loadbalancer.server.port=8080"
    networks:
      - traefik

networks:
  traefik:
    external: true