name: notifi
on: [push]

jobs:
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            ${{ secrets.DEPLOY_CMD }} ${{ github.sha }}
